Feature/update footer order align
NEAR-Edu/near-certification-tools pull request #9
Opened 2022-02-17 13:05 UTC by ozanisgor

@ryancwalsh according to https://github.com/NEAR-Edu/near-certification-tools/pull/7#issuecomment-1041509218 I did below changes.

1. Update footer content order to `Logo > Icons > Jobs`
2. Align footer left (In this point I am not sure did I understand correctly)
   - For this change I remove the space at left and right for the entire footer but I might be misunderstood so because of that I did an alternative version which align the entire footer to left and creates a space at right. 

   
![17 02 22_layout_before](https://user-images.githubusercontent.com/70068338/154486227-8140e177-54ba-468d-9381-b64dd92925e6.png)

![17 02 22_layout_after](https://user-images.githubusercontent.com/70068338/154486296-c51ac512-9648-45f0-9084-1342f95b5c69.png)

### **2nd Version**

![17 02 22_layout_after_v2](https://user-images.githubusercontent.com/70068338/154486308-cfcdeecb-b5fa-47de-9b4e-7e881eca36d5.png)

2022-02-17 14:07 UTC, ryancwalsh requested changes
What I meant is to have all content of the footer left-aligned, without using 3 columns anymore.

More like this: 
![image](https://user-images.githubusercontent.com/2086493/154497813-cbae9b4d-209c-42af-8aec-b1b742177095.png)

But after you condense down to 1 "column" like that, you might want to experiment with centering the whole footer to see whether it looks better than the left-aligned example I just showed here.

2022-02-18 14:09 UTC, ozanisgor commented
@ryancwalsh I think the left-align version is looking better.  This one was challanging because of responsivenes. It looks good but when you change to small screen logo getting smaller than other items. I tried to figure out but could not find the solution.

I tried to show what i mean by loom video:
https://www.loom.com/share/2633635447434b538e4153c951d24367

![18 02 22_footer-align-left_after](https://user-images.githubusercontent.com/70068338/154695071-5c0e2e45-f7f3-4a66-be54-7740c90e2e38.png)

PREVIOUS versions

![18 02 22_footer-align-left_certered-version](https://user-images.githubusercontent.com/70068338/154696100-33885771-a520-462f-920a-0383c14600f8.png)


![17 02 22_layout_after](https://user-images.githubusercontent.com/70068338/154695186-21fc09d7-bbda-495a-a3ee-7ff805489a17.png)

2022-02-18 14:44 UTC, ryancwalsh commented
@ozanisgor I just made this video for you and then afterwards saw your video here and comments.

https://www.loom.com/share/d728ccf6b9084378a2dac4ae461d89c8

Most of my video is still what I wanted to say, but now that I see your helpful responsiveness demo, I think (unlike what I said in the video) it does make sense to have an inline-block around the social icons. 

In the video I'd said that you could optionally have no element to contain them and that they could exist as direct siblings of the other part of the footer. 

But I think having them bundled together makes sense. But not acting as a column or with padding.

2022-02-21 13:55 UTC, ozanisgor commented
@ryancwalsh thank you for the video to explain detailed. I hope I understand what you mean. I remove the unnecessary divs and tried to bring all content into one column. While doing this tried to keep responsiveness. I tried to use `inline-block` but somehow it doesn't work or I coundn't manage to make that work but with flex(according to VSCode they are doing the same) I belive now seems like what you want to see. I tried to explain it with a video and some screenshots below.

I didn't push the code because maybe this not what you want. I can push immedately if you want.

BEFORE

![before_footer-align-left](https://user-images.githubusercontent.com/70068338/154966981-1ce84b9b-91e7-4324-bbf8-d6fc963c4234.png)

AFTER

![after_footer-align-left](https://user-images.githubusercontent.com/70068338/154967021-87f09fd7-b546-476e-9607-3b01285bfb05.png)

AFTER-Centered 

![after_footer-align-center](https://user-images.githubusercontent.com/70068338/154967184-a7a48e26-0271-4acc-983f-30a4c881e7e4.png)

AFTER-Small-Devices

![after_footer-align-center_small-devices](https://user-images.githubusercontent.com/70068338/154967199-b688e700-fd79-406d-8adc-65083f146d78.png)

AFTER-Small-Devices with `inline-block`

Also wider screens have the same wierd looking.

![after_footer-align-center_small-devices_inline-block](https://user-images.githubusercontent.com/70068338/154967226-ac7b396a-3c4d-4b92-96b2-daedaf30bdf0.png)

VIDEO

When I replay the video I've tnoticed voice is lagging I hope It won't be a problem for you to follow.

https://www.loom.com/share/97cb91d034fb494bba9c6a926b14d8a3

2022-02-22 16:39 UTC, ozanisgor commented
@ryancwalsh sorry for the problem with the video. I pushed the code as `centered` one. 
I didn't push at the first place because maybe I misunderstood what you want and didn't want to mess.

2022-02-22 19:29 UTC, ryancwalsh commented on web-app/components/Footer.tsx
> +          <img className="min-w-full" alt="NEAR University logo" width="200px" src="/near_university_logo.svg" />{' '}
This `{' '}` feels weird. Let's fix it in a future branch.

2022-02-22 19:30 UTC, merged